# Generated by Django 4.1.3 on 2022-12-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_key_created_at_key_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='slug',
            field=models.SlugField(default='', max_length=25, unique=True),
        ),
    ]
