# Generated by Django 4.1.3 on 2022-12-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_key_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(default='', max_length=50)),
                ('sub_breed', models.CharField(default='', max_length=50)),
                ('original_url', models.CharField(default='', max_length=250)),
                ('transformed_url', models.CharField(default='', max_length=250)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
